In [15]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
iris=datasets.load_iris()

In [16]:
# Forming  dataframe
data=pd.DataFrame(iris.data, columns=iris.feature_names)
data['target']=iris.target
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [17]:
#Split training and testing data

y=df['target']
x=df.drop('target',axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.70,test_size=0.30, random_state=0)

In [20]:
#DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
dt_pred = dt_model.predict(x_test)

msee1 = mean_squared_error(y_test, dt_pred)
ra1 = r2_score(y_test, dt_pred)
maee1 = mean_absolute_error(y_test,dt_pred)
print("Mean Squared Error:",msee1)
print("R score:",ra1)
print("Mean Absolute Error:",maee1)
print('accuracy score:')
print(accuracy_score(y_test,dt_pred))

Mean Squared Error: 0.022222222222222223
R score: 0.9621848739495799
Mean Absolute Error: 0.022222222222222223
accuracy score:
0.9777777777777777